### ISSUE TITLE
template에 예상 소요 시간, 실제 소요 시간을 추가한다

### ISSUE THREAD

**Issue by drunkenhw** [woowacourse-teams/2023-car-ffeine#165]
### 🔨 Describe

예상 소요 시간, 실제 소요 시간을 매번 입력하기 귀찮으니 template에 추가하는 것이 좋을 것 같습니다.

### ✅ Tasks

- [ ] issue template에 예상 소요 시간 추가
- [ ] pull requests template에 실제 소요 시간 추가

**Comment by gabrielyoon7** [comment]
동의 합니다
