### ISSUE TITLE
@style 경로를 참조할 수 없는 에러를 개선한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#189]
### 🐞 Describe

현재 웹팩에 `@style` 경로 참조에 대한 설정이 추가되어 있지 않아 `@style` 경로를 참조할 수 없는 오류가 발생하고 있다.

### 🌏 Environment

윈도우

### 🕰️ Estimated Time of Completion

1분

**Comment by gabrielyoon7** [comment]
긴급긴급
