### ISSUE TITLE
지도 범위로 조회 API를 작성한다

### ISSUE THREAD

**Issue by be-student** [woowacourse-teams/2023-car-ffeine#20]
### ✨ Describe

지도 범위로 조회 API 작성

### ✅ Tasks

- [ ] 지도 범위로 조회 API 작성

**Comment by sosow0212** [comment]
이거 박스터가 진행한 28번 이슈랑 같은 이슈라서 닫아도 될 것 같습니다~
https://github.com/woowacourse-teams/2023-car-ffeine/pull/44
