### ISSUE TITLE
PC 버전 지도 간단 정보 가려지는 문제를 해결한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#255]
### 🔨 Describe

![image](https://github.com/woowacourse-teams/2023-car-ffeine/assets/77326660/5c73694d-f54f-4e10-9a31-afee3f1f4361)

지도의 센터 좌표는 항상 고정되어 있어 좌측 메뉴가 펼쳐져 있을 경우 간단 정보가 가려지는 문제가 발생한다.

### ✅ Tasks

- [ ] 문제 해결

**Comment by gabrielyoon7** [comment]
이미 해결된 문제 입니다
