### ISSUE TITLE
여러 충전 사업자가 같이 선택되는 버그

### ISSUE THREAD

**Issue by woosung1223** [woowacourse-teams/2023-car-ffeine#379]
### 🐞 Describe

충전 사업자 탭에 '광주' 가 두 개 있는데, 하나를 누르면 다른 하나도 같이 눌러집니다!

<img width="267" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/78679830/82467c1d-d5a1-4957-a666-ae5c9f65336e">
<img width="261" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/78679830/f959c2de-ee40-463b-8a44-418d0a9dc73c">

### 🌏 Environment

OS: macOS
browser: Chrome

**Comment by kyw0716** [comment]
제보해주신 버그 수정 완료했습니다!
