### ISSUE TITLE
사용하면서 불편하거나 어떤 기능인지 파악하기 힘든 부분

### ISSUE THREAD

**Issue by MoonJeWoong** [woowacourse-teams/2023-car-ffeine#380]
### 🐞 Describe

- 충전소 상태 불일치 신고 이후 언제 다시 신고가 가능한지 파악하기 힘들었습니다.
- 충전소마다 급속, 완속 탭에서 확인할 수 있는 정보가 무엇인지 이해하기가 힘들었습니다.
- 카페인 로고에 커서를 올렸을 때 클릭을 할 수 있는 것처럼 표시되지만 클릭 시 아무것도 발생하지 않았습니다.

### 📄 Logs

```shell
describe에 작성했습니다.
```

### 🌏 Environment

describe에 작성했습니다.

### 🕰️ Estimated Time of Completion

describe에 작성했습니다.

### 🙋🏻 More

describe에 작성했습니다.

**Comment by gabrielyoon7** [comment]
반영되었습니다. 감사합니다.
