### ISSUE TITLE
rest-docs, ascii docs 으로 문서화를 진행한다

### ISSUE THREAD

**Issue by be-student** [woowacourse-teams/2023-car-ffeine#4]
### ✨ Describe

API 문서화 도구중 rest-docs 를 사용했습니다

### rest-docs 를 사용한 이유

- swagger 와 비교했을 때, api 문서의 신뢰성을 더 보장할 수 있습니다.
- controller 코드의 가독성이 restdocs 보다 떨어집니다

### asciidoc 을 사용한 이유

markdown 으로 작성할 수 있지만, include 문을 사용하기 어렵습니다. 

```
ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
= Car-ffeine
:doctype: book
:toc: left
:source-highlighter: highlightjs
:sectlinks:

include::home.adoc[]

```
위의 코드와 같이 include 문을 통해서 다른 adoc 파일을 가져올 수 있지만, markdown 의 경우 사용하기 힘든 상황입니다.

### mockMvc 를 사용한 이유

restassured 와 비교했을 때, restassured 는 필수적으로 ```@SpringBootTest``` 와 함께 사용해야 합니다.

이 부분이 성능상 안좋은 영향을 끼칠 것 같아서 사용하지 않았습니다

### restdocs 적용하기

- [x] restdocs 설치하기
- [x] asciidoc 설정하기
- [x] 예시 코드 몇개 만들기

### 🙋🏻 More

restdocs 를 편하게 볼 수 있는 플러그인

https://plugins.jetbrains.com/plugin/7391-asciidoc

markdown 으로 사용하는 것이 힘든 이유

https://jojoldu.tistory.com/289

todo restdocs 작성시 참고할만한 내용들

https://backtony.github.io/spring/2021-10-15-spring-test-3/

**Comment by drunkenhw** [comment]
예시 코드는 좋은데 굳이 필요할까 싶어요!
gradle 세팅만 커밋하는거 어때요?

**Comment by be-student** [comment]
아주 좋아요!
