### ISSUE TITLE
검색 결과 마커에 사용 가능한 충전기 개수를 로드하는 로직을 개선한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#802]
### 🔨 Describe

현재 충전소 마커 조회를 위한 API로 (위도, 경도 기반 조회) 충전소를 조회하여 검색 결과 충전소 마커에 보여지는 충전기 개수를 렌더링하고 있습니다. 이때, 델타 값을 아주 작게 줘서 마커를 조회하는 방식을 사용하고 있는데 이 부분에서 어떤 오류가 발생할지 몰라 개선이 필요하다고 판단됩니다.

### ✅ Tasks

- [x] 충전소 ID 기반 세부 정보 요청을 통해 이용 가능한 충전기 개수를 렌더링하도록 수정한다.

### 🕰️ Estimated Time of Completion

2시간

**Comment by gabrielyoon7** [comment]
이거는 백엔드 크루에게 `특정 충전소 id의 가용 충전기 갯수를 알아내는 api`를 하나 더 뚫어달라 하는게 나을 수도 있습니다.
그렇게 하면 현재 구조를 거의 완벽히 유지할 수 있을 것 같아요.

**Comment by kyw0716** [comment]
충전소 상세 정보 요청으로 충분히 가능할 것 같아서 이걸 먼저 시도해보려 합니다. 이렇게 해도 충분히 지금 구조를 유지하면서 기능을 구현할 수 있습니다!!
