### ISSUE TITLE
모달 디자인을 개선한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#839]
### 🔨 Describe

현재 모바일에서 모달 너비가 너무 작은 느낌이 들어 디바이스에 맞춤형 너비를 제공하도록 변경합니다.

### ✅ Tasks

- [x] 모달 디자인 개선

### 🕰️ Estimated Time of Completion

1시간

**Comment by gabrielyoon7** [comment]
모달 갈아엎어주세여...
시간 없어서 대충 만든거라 ...

**Comment by feb-dain** [comment]
> 모달 갈아엎어주세여... 시간 없어서 대충 만든거라 ...

모달 공통 컴포넌트여?? 그거슨 나중에...

**Comment by gabrielyoon7** [comment]
> > 모달 갈아엎어주세여... 시간 없어서 대충 만든거라 ...
> 
> 모달 공통 컴포넌트여?? 그거슨 나중에...

아하...
