### ISSUE TITLE
서버 클러스터링 캐싱에 의해 줌 레벨 변화에 재 요청을 보내지 않는 오류를 수정한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#860]
### 🐞 Describe

이전 충전소 마커 캐싱과 동일한 로직으로 클러스터링 마커에 대한 캐싱도 진행했더니 넓은 영역의 지도를 보다가 더 좁은 영역을 보기 위해 지도의 줌 레벨을 증가시켰을 때 다시 재요청을 보내지 않는 문제가 있습니다.

이를 수정하기 위해 줌 레벨을 더 세분화해서 서버 클러스터 재요청을 발생시키는 로직이 추가되어야할 것 같습니다.
(현재 줌 레벨을 세분화하여 충전소 마커의 UI를 디폴트 마커, 카페인 마커로 분기처리하는 부분이 있는데 이 부분을 참고하면 좋을 것 같습니다.)

### 🌏 Environment

모든 디바이스

### 🕰️ Estimated Time of Completion

3시간

**Comment by feb-dain** [comment]
모바일에서 화면을 조금 이동했을 때 다른 서버 클러스터링 마커가 있으면 기존에 있던 클러스터링 위치가 바뀌어요..! (무슨 말인지 모르겠다면 월요일날 보여드리겠습니다) 뭔가 이상하게 느껴지는데 displayPosition 바깥으로 나가지 않으면 원래 위치 그대로 클러스터링 띄워주는 건 별로일까요? 아니면 이 부분은 현재 어쩔 수 없는 부분인가요?

**Comment by kyw0716** [comment]
오프라인 그림 설명 완료했습니다~
